-- Describe POKEMON_EVOLUTION
CREATE TABLE pokemon_evolution (
	id INTEGER NOT NULL, 
	evolved_species_id INTEGER NOT NULL, 
	evolution_trigger_id INTEGER NOT NULL, 
	trigger_item_id INTEGER, 
	minimum_level INTEGER, 
	gender_id INTEGER, 
	location_id INTEGER, 
	held_item_id INTEGER, 
	time_of_day VARCHAR(5), 
	known_move_id INTEGER, 
	known_move_type_id INTEGER, 
	minimum_happiness INTEGER, 
	minimum_beauty INTEGER, 
	minimum_affection INTEGER, 
	relative_physical_stats INTEGER, 
	party_species_id INTEGER, 
	party_type_id INTEGER, 
	trade_species_id INTEGER, 
	needs_overworld_rain BOOLEAN NOT NULL, 
	turn_upside_down BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(evolved_species_id) REFERENCES pokemon_species (id), 
	FOREIGN KEY(evolution_trigger_id) REFERENCES evolution_triggers (id), 
	FOREIGN KEY(trigger_item_id) REFERENCES items (id), 
	FOREIGN KEY(gender_id) REFERENCES genders (id), 
	FOREIGN KEY(location_id) REFERENCES locations (id), 
	FOREIGN KEY(held_item_id) REFERENCES items (id), 
	CONSTRAINT pokemon_evolution_time_of_day CHECK (time_of_day IN ('day', 'night')), 
	FOREIGN KEY(known_move_id) REFERENCES moves (id), 
	FOREIGN KEY(known_move_type_id) REFERENCES types (id), 
	FOREIGN KEY(party_species_id) REFERENCES pokemon_species (id), 
	FOREIGN KEY(party_type_id) REFERENCES types (id), 
	FOREIGN KEY(trade_species_id) REFERENCES pokemon_species (id), 
	CHECK (needs_overworld_rain IN (0, 1)), 
	CHECK (turn_upside_down IN (0, 1))
)
