BEGIN TRANSACTION;
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('1', '9', 'Level up', 'Learned when a Pokémon reaches a certain level.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('2', '9', 'Egg', 'Appears on a newly-hatched Pokémon, if the father had the same move.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('3', '9', 'Tutor', 'Can be taught at any time by an NPC.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('4', '9', 'Machine', 'Can be taught at any time by using a TM or HM.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('5', '9', 'Stadium: Surfing Pikachu', 'Learned when a non-rental Pikachu helps beat Prime Cup Master Ball R-2.  It must participate in every battle, and you must win with no continues.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('6', '9', 'Volt Tackle Pichu', 'Appears on a Pichu whose mother was holding a Light Ball.  The father cannot be Ditto.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('7', '9', 'Colosseum: Purification', 'Appears on a Shadow Pokémon as it becomes increasingly purified.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('8', '9', 'XD: Shadow', 'Appears on a Snatched Shadow Pokémon.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('9', '9', 'XD: Purification', 'Appears on a Shadow Pokémon as it becomes increasingly purified.');
insert into pokemon_move_method_prose ("pokemon_move_method_id", "local_language_id", "name", "description") values ('10', '9', 'Rotom Form', 'Appears when Rotom changes to this form.  Disappears if Rotom becomes another form and this move can only be learned by form change.');
COMMIT;
