BEGIN TRANSACTION;
insert into stats ("id", "damage_class_id", "identifier", "is_battle_only", "game_index") values ('1', NULL, 'hp', '0', '1');
insert into stats ("id", "damage_class_id", "identifier", "is_battle_only", "game_index") values ('2', '2', 'attack', '0', '2');
insert into stats ("id", "damage_class_id", "identifier", "is_battle_only", "game_index") values ('3', '2', 'defense', '0', '3');
insert into stats ("id", "damage_class_id", "identifier", "is_battle_only", "game_index") values ('4', '3', 'special-attack', '0', '5');
insert into stats ("id", "damage_class_id", "identifier", "is_battle_only", "game_index") values ('5', '3', 'special-defense', '0', '6');
insert into stats ("id", "damage_class_id", "identifier", "is_battle_only", "game_index") values ('6', NULL, 'speed', '0', '4');
insert into stats ("id", "damage_class_id", "identifier", "is_battle_only", "game_index") values ('7', NULL, 'accuracy', '1', NULL);
insert into stats ("id", "damage_class_id", "identifier", "is_battle_only", "game_index") values ('8', NULL, 'evasion', '1', NULL);
COMMIT;
