BEGIN TRANSACTION;
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('1', '9', 'Bulbasaur', 'Seed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('2', '9', 'Ivysaur', 'Seed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('3', '9', 'Venusaur', 'Seed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('4', '9', 'Charmander', 'Lizard');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('5', '9', 'Charmeleon', 'Flame');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('6', '9', 'Charizard', 'Flame');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('7', '9', 'Squirtle', 'Tiny Turtle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('8', '9', 'Wartortle', 'Turtle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('9', '9', 'Blastoise', 'Shellfish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('10', '9', 'Caterpie', 'Worm');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('11', '9', 'Metapod', 'Cocoon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('12', '9', 'Butterfree', 'Butterfly');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('13', '9', 'Weedle', 'Hairy Bug');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('14', '9', 'Kakuna', 'Cocoon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('15', '9', 'Beedrill', 'Poison Bee');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('16', '9', 'Pidgey', 'Tiny Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('17', '9', 'Pidgeotto', 'Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('18', '9', 'Pidgeot', 'Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('19', '9', 'Rattata', 'Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('20', '9', 'Raticate', 'Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('21', '9', 'Spearow', 'Tiny Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('22', '9', 'Fearow', 'Beak');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('23', '9', 'Ekans', 'Snake');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('24', '9', 'Arbok', 'Cobra');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('25', '9', 'Pikachu', 'Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('26', '9', 'Raichu', 'Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('27', '9', 'Sandshrew', 'Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('28', '9', 'Sandslash', 'Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('29', '9', 'Nidoran♀', 'Poison Pin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('30', '9', 'Nidorina', 'Poison Pin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('31', '9', 'Nidoqueen', 'Drill');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('32', '9', 'Nidoran♂', 'Poison Pin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('33', '9', 'Nidorino', 'Poison Pin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('34', '9', 'Nidoking', 'Drill');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('35', '9', 'Clefairy', 'Fairy');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('36', '9', 'Clefable', 'Fairy');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('37', '9', 'Vulpix', 'Fox');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('38', '9', 'Ninetales', 'Fox');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('39', '9', 'Jigglypuff', 'Balloon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('40', '9', 'Wigglytuff', 'Balloon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('41', '9', 'Zubat', 'Bat');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('42', '9', 'Golbat', 'Bat');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('43', '9', 'Oddish', 'Weed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('44', '9', 'Gloom', 'Weed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('45', '9', 'Vileplume', 'Flower');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('46', '9', 'Paras', 'Mushroom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('47', '9', 'Parasect', 'Mushroom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('48', '9', 'Venonat', 'Insect');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('49', '9', 'Venomoth', 'Poison Moth');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('50', '9', 'Diglett', 'Mole');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('51', '9', 'Dugtrio', 'Mole');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('52', '9', 'Meowth', 'Scratch Cat');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('53', '9', 'Persian', 'Classy Cat');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('54', '9', 'Psyduck', 'Duck');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('55', '9', 'Golduck', 'Duck');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('56', '9', 'Mankey', 'Pig Monkey');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('57', '9', 'Primeape', 'Pig Monkey');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('58', '9', 'Growlithe', 'Puppy');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('59', '9', 'Arcanine', 'Legendary');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('60', '9', 'Poliwag', 'Tadpole');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('61', '9', 'Poliwhirl', 'Tadpole');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('62', '9', 'Poliwrath', 'Tadpole');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('63', '9', 'Abra', 'Psi');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('64', '9', 'Kadabra', 'Psi');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('65', '9', 'Alakazam', 'Psi');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('66', '9', 'Machop', 'Superpower');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('67', '9', 'Machoke', 'Superpower');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('68', '9', 'Machamp', 'Superpower');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('69', '9', 'Bellsprout', 'Flower');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('70', '9', 'Weepinbell', 'Flycatcher');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('71', '9', 'Victreebel', 'Flycatcher');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('72', '9', 'Tentacool', 'Jellyfish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('73', '9', 'Tentacruel', 'Jellyfish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('74', '9', 'Geodude', 'Rock');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('75', '9', 'Graveler', 'Rock');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('76', '9', 'Golem', 'Megaton');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('77', '9', 'Ponyta', 'Fire Horse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('78', '9', 'Rapidash', 'Fire Horse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('79', '9', 'Slowpoke', 'Dopey');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('80', '9', 'Slowbro', 'Hermit Crab');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('81', '9', 'Magnemite', 'Magnet');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('82', '9', 'Magneton', 'Magnet');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('83', '9', 'Farfetch''d', 'Wild Duck');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('84', '9', 'Doduo', 'Twin Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('85', '9', 'Dodrio', 'Triple Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('86', '9', 'Seel', 'Sea Lion');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('87', '9', 'Dewgong', 'Sea Lion');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('88', '9', 'Grimer', 'Sludge');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('89', '9', 'Muk', 'Sludge');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('90', '9', 'Shellder', 'Bivalve');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('91', '9', 'Cloyster', 'Bivalve');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('92', '9', 'Gastly', 'Gas');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('93', '9', 'Haunter', 'Gas');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('94', '9', 'Gengar', 'Shadow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('95', '9', 'Onix', 'Rock Snake');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('96', '9', 'Drowzee', 'Hypnosis');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('97', '9', 'Hypno', 'Hypnosis');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('98', '9', 'Krabby', 'River Crab');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('99', '9', 'Kingler', 'Pincer');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('100', '9', 'Voltorb', 'Ball');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('101', '9', 'Electrode', 'Ball');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('102', '9', 'Exeggcute', 'Egg');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('103', '9', 'Exeggutor', 'Coconut');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('104', '9', 'Cubone', 'Lonely');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('105', '9', 'Marowak', 'Bone Keeper');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('106', '9', 'Hitmonlee', 'Kicking');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('107', '9', 'Hitmonchan', 'Punching');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('108', '9', 'Lickitung', 'Licking');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('109', '9', 'Koffing', 'Poison Gas');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('110', '9', 'Weezing', 'Poison Gas');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('111', '9', 'Rhyhorn', 'Spikes');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('112', '9', 'Rhydon', 'Drill');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('113', '9', 'Chansey', 'Egg');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('114', '9', 'Tangela', 'Vine');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('115', '9', 'Kangaskhan', 'Parent');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('116', '9', 'Horsea', 'Dragon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('117', '9', 'Seadra', 'Dragon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('118', '9', 'Goldeen', 'Goldfish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('119', '9', 'Seaking', 'Goldfish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('120', '9', 'Staryu', 'Star Shape');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('121', '9', 'Starmie', 'Mysterious');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('122', '9', 'Mr. Mime', 'Barrier');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('123', '9', 'Scyther', 'Mantis');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('124', '9', 'Jynx', 'Human Shape');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('125', '9', 'Electabuzz', 'Electric');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('126', '9', 'Magmar', 'Spitfire');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('127', '9', 'Pinsir', 'Stag Beetle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('128', '9', 'Tauros', 'Wild Bull');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('129', '9', 'Magikarp', 'Fish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('130', '9', 'Gyarados', 'Atrocious');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('131', '9', 'Lapras', 'Transport');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('132', '9', 'Ditto', 'Transform');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('133', '9', 'Eevee', 'Evolution');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('134', '9', 'Vaporeon', 'Bubble Jet');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('135', '9', 'Jolteon', 'Lightning');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('136', '9', 'Flareon', 'Flame');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('137', '9', 'Porygon', 'Virtual');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('138', '9', 'Omanyte', 'Spiral');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('139', '9', 'Omastar', 'Spiral');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('140', '9', 'Kabuto', 'Shellfish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('141', '9', 'Kabutops', 'Shellfish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('142', '9', 'Aerodactyl', 'Fossil');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('143', '9', 'Snorlax', 'Sleeping');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('144', '9', 'Articuno', 'Freeze');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('145', '9', 'Zapdos', 'Electric');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('146', '9', 'Moltres', 'Flame');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('147', '9', 'Dratini', 'Dragon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('148', '9', 'Dragonair', 'Dragon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('149', '9', 'Dragonite', 'Dragon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('150', '9', 'Mewtwo', 'Genetic');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('151', '9', 'Mew', 'New Species');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('152', '9', 'Chikorita', 'Leaf');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('153', '9', 'Bayleef', 'Leaf');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('154', '9', 'Meganium', 'Herb');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('155', '9', 'Cyndaquil', 'Fire Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('156', '9', 'Quilava', 'Volcano');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('157', '9', 'Typhlosion', 'Volcano');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('158', '9', 'Totodile', 'Big Jaw');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('159', '9', 'Croconaw', 'Big Jaw');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('160', '9', 'Feraligatr', 'Big Jaw');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('161', '9', 'Sentret', 'Scout');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('162', '9', 'Furret', 'Long Body');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('163', '9', 'Hoothoot', 'Owl');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('164', '9', 'Noctowl', 'Owl');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('165', '9', 'Ledyba', 'Five Star');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('166', '9', 'Ledian', 'Five Star');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('167', '9', 'Spinarak', 'String Spit');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('168', '9', 'Ariados', 'Long Leg');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('169', '9', 'Crobat', 'Bat');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('170', '9', 'Chinchou', 'Angler');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('171', '9', 'Lanturn', 'Light');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('172', '9', 'Pichu', 'Tiny Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('173', '9', 'Cleffa', 'Star Shape');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('174', '9', 'Igglybuff', 'Balloon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('175', '9', 'Togepi', 'Spike Ball');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('176', '9', 'Togetic', 'Happiness');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('177', '9', 'Natu', 'Tiny Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('178', '9', 'Xatu', 'Mystic');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('179', '9', 'Mareep', 'Wool');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('180', '9', 'Flaaffy', 'Wool');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('181', '9', 'Ampharos', 'Light');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('182', '9', 'Bellossom', 'Flower');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('183', '9', 'Marill', 'Aqua Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('184', '9', 'Azumarill', 'Aqua Rabbit');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('185', '9', 'Sudowoodo', 'Imitation');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('186', '9', 'Politoed', 'Frog');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('187', '9', 'Hoppip', 'Cottonweed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('188', '9', 'Skiploom', 'Cottonweed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('189', '9', 'Jumpluff', 'Cottonweed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('190', '9', 'Aipom', 'Long Tail');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('191', '9', 'Sunkern', 'Seed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('192', '9', 'Sunflora', 'Sun');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('193', '9', 'Yanma', 'Clear Wing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('194', '9', 'Wooper', 'Water Fish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('195', '9', 'Quagsire', 'Water Fish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('196', '9', 'Espeon', 'Sun');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('197', '9', 'Umbreon', 'Moonlight');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('198', '9', 'Murkrow', 'Darkness');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('199', '9', 'Slowking', 'Royal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('200', '9', 'Misdreavus', 'Screech');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('201', '9', 'Unown', 'Symbol');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('202', '9', 'Wobbuffet', 'Patient');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('203', '9', 'Girafarig', 'Long Neck');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('204', '9', 'Pineco', 'Bagworm');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('205', '9', 'Forretress', 'Bagworm');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('206', '9', 'Dunsparce', 'Land Snake');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('207', '9', 'Gligar', 'FlyScorpion');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('208', '9', 'Steelix', 'Iron Snake');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('209', '9', 'Snubbull', 'Fairy');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('210', '9', 'Granbull', 'Fairy');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('211', '9', 'Qwilfish', 'Balloon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('212', '9', 'Scizor', 'Pincer');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('213', '9', 'Shuckle', 'Mold');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('214', '9', 'Heracross', 'Single Horn');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('215', '9', 'Sneasel', 'Sharp Claw');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('216', '9', 'Teddiursa', 'Little Bear');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('217', '9', 'Ursaring', 'Hibernator');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('218', '9', 'Slugma', 'Lava');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('219', '9', 'Magcargo', 'Lava');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('220', '9', 'Swinub', 'Pig');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('221', '9', 'Piloswine', 'Swine');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('222', '9', 'Corsola', 'Coral');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('223', '9', 'Remoraid', 'Jet');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('224', '9', 'Octillery', 'Jet');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('225', '9', 'Delibird', 'Delivery');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('226', '9', 'Mantine', 'Kite');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('227', '9', 'Skarmory', 'Armor Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('228', '9', 'Houndour', 'Dark');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('229', '9', 'Houndoom', 'Dark');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('230', '9', 'Kingdra', 'Dragon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('231', '9', 'Phanpy', 'Long Nose');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('232', '9', 'Donphan', 'Armor');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('233', '9', 'Porygon2', 'Virtual');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('234', '9', 'Stantler', 'Big Horn');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('235', '9', 'Smeargle', 'Painter');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('236', '9', 'Tyrogue', 'Scuffle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('237', '9', 'Hitmontop', 'Handstand');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('238', '9', 'Smoochum', 'Kiss');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('239', '9', 'Elekid', 'Electric');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('240', '9', 'Magby', 'Live Coal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('241', '9', 'Miltank', 'Milk Cow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('242', '9', 'Blissey', 'Happiness');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('243', '9', 'Raikou', 'Thunder');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('244', '9', 'Entei', 'Volcano');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('245', '9', 'Suicune', 'Aurora');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('246', '9', 'Larvitar', 'Rock Skin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('247', '9', 'Pupitar', 'Hard Shell');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('248', '9', 'Tyranitar', 'Armor');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('249', '9', 'Lugia', 'Diving');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('250', '9', 'Ho-Oh', 'Rainbow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('251', '9', 'Celebi', 'Time Travel');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('252', '9', 'Treecko', 'Wood Gecko');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('253', '9', 'Grovyle', 'Wood Gecko');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('254', '9', 'Sceptile', 'Forest');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('255', '9', 'Torchic', 'Chick');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('256', '9', 'Combusken', 'Young Fowl');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('257', '9', 'Blaziken', 'Blaze');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('258', '9', 'Mudkip', 'Mud Fish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('259', '9', 'Marshtomp', 'Mud Fish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('260', '9', 'Swampert', 'Mud Fish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('261', '9', 'Poochyena', 'Bite');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('262', '9', 'Mightyena', 'Bite');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('263', '9', 'Zigzagoon', 'TinyRaccoon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('264', '9', 'Linoone', 'Rushing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('265', '9', 'Wurmple', 'Worm');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('266', '9', 'Silcoon', 'Cocoon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('267', '9', 'Beautifly', 'Butterfly');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('268', '9', 'Cascoon', 'Cocoon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('269', '9', 'Dustox', 'Poison Moth');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('270', '9', 'Lotad', 'Water Weed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('271', '9', 'Lombre', 'Jolly');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('272', '9', 'Ludicolo', 'Carefree');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('273', '9', 'Seedot', 'Acorn');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('274', '9', 'Nuzleaf', 'Wily');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('275', '9', 'Shiftry', 'Wicked');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('276', '9', 'Taillow', 'TinySwallow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('277', '9', 'Swellow', 'Swallow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('278', '9', 'Wingull', 'Seagull');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('279', '9', 'Pelipper', 'Water Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('280', '9', 'Ralts', 'Feeling');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('281', '9', 'Kirlia', 'Emotion');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('282', '9', 'Gardevoir', 'Embrace');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('283', '9', 'Surskit', 'Pond Skater');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('284', '9', 'Masquerain', 'Eyeball');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('285', '9', 'Shroomish', 'Mushroom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('286', '9', 'Breloom', 'Mushroom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('287', '9', 'Slakoth', 'Slacker');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('288', '9', 'Vigoroth', 'Wild Monkey');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('289', '9', 'Slaking', 'Lazy');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('290', '9', 'Nincada', 'Trainee');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('291', '9', 'Ninjask', 'Ninja');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('292', '9', 'Shedinja', 'Shed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('293', '9', 'Whismur', 'Whisper');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('294', '9', 'Loudred', 'Big Voice');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('295', '9', 'Exploud', 'Loud Noise');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('296', '9', 'Makuhita', 'Guts');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('297', '9', 'Hariyama', 'Arm Thrust');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('298', '9', 'Azurill', 'Polka Dot');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('299', '9', 'Nosepass', 'Compass');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('300', '9', 'Skitty', 'Kitten');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('301', '9', 'Delcatty', 'Prim');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('302', '9', 'Sableye', 'Darkness');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('303', '9', 'Mawile', 'Deceiver');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('304', '9', 'Aron', 'Iron Armor');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('305', '9', 'Lairon', 'Iron Armor');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('306', '9', 'Aggron', 'Iron Armor');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('307', '9', 'Meditite', 'Meditate');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('308', '9', 'Medicham', 'Meditate');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('309', '9', 'Electrike', 'Lightning');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('310', '9', 'Manectric', 'Discharge');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('311', '9', 'Plusle', 'Cheering');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('312', '9', 'Minun', 'Cheering');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('313', '9', 'Volbeat', 'Firefly');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('314', '9', 'Illumise', 'Firefly');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('315', '9', 'Roselia', 'Thorn');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('316', '9', 'Gulpin', 'Stomach');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('317', '9', 'Swalot', 'Poison Bag');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('318', '9', 'Carvanha', 'Savage');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('319', '9', 'Sharpedo', 'Brutal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('320', '9', 'Wailmer', 'Ball Whale');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('321', '9', 'Wailord', 'Float Whale');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('322', '9', 'Numel', 'Numb');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('323', '9', 'Camerupt', 'Eruption');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('324', '9', 'Torkoal', 'Coal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('325', '9', 'Spoink', 'Bounce');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('326', '9', 'Grumpig', 'Manipulate');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('327', '9', 'Spinda', 'Spot Panda');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('328', '9', 'Trapinch', 'Ant Pit');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('329', '9', 'Vibrava', 'Vibration');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('330', '9', 'Flygon', 'Mystic');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('331', '9', 'Cacnea', 'Cactus');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('332', '9', 'Cacturne', 'Scarecrow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('333', '9', 'Swablu', 'Cotton Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('334', '9', 'Altaria', 'Humming');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('335', '9', 'Zangoose', 'Cat Ferret');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('336', '9', 'Seviper', 'Fang Snake');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('337', '9', 'Lunatone', 'Meteorite');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('338', '9', 'Solrock', 'Meteorite');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('339', '9', 'Barboach', 'Whiskers');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('340', '9', 'Whiscash', 'Whiskers');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('341', '9', 'Corphish', 'Ruffian');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('342', '9', 'Crawdaunt', 'Rogue');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('343', '9', 'Baltoy', 'Clay Doll');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('344', '9', 'Claydol', 'Clay Doll');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('345', '9', 'Lileep', 'Sea Lily');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('346', '9', 'Cradily', 'Barnacle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('347', '9', 'Anorith', 'Old Shrimp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('348', '9', 'Armaldo', 'Plate');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('349', '9', 'Feebas', 'Fish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('350', '9', 'Milotic', 'Tender');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('351', '9', 'Castform', 'Weather');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('352', '9', 'Kecleon', 'Color Swap');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('353', '9', 'Shuppet', 'Puppet');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('354', '9', 'Banette', 'Marionette');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('355', '9', 'Duskull', 'Requiem');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('356', '9', 'Dusclops', 'Beckon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('357', '9', 'Tropius', 'Fruit');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('358', '9', 'Chimecho', 'Wind Chime');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('359', '9', 'Absol', 'Disaster');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('360', '9', 'Wynaut', 'Bright');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('361', '9', 'Snorunt', 'Snow Hat');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('362', '9', 'Glalie', 'Face');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('363', '9', 'Spheal', 'Clap');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('364', '9', 'Sealeo', 'Ball Roll');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('365', '9', 'Walrein', 'Ice Break');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('366', '9', 'Clamperl', 'Bivalve');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('367', '9', 'Huntail', 'Deep Sea');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('368', '9', 'Gorebyss', 'South Sea');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('369', '9', 'Relicanth', 'Longevity');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('370', '9', 'Luvdisc', 'Rendezvous');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('371', '9', 'Bagon', 'Rock Head');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('372', '9', 'Shelgon', 'Endurance');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('373', '9', 'Salamence', 'Dragon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('374', '9', 'Beldum', 'Iron Ball');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('375', '9', 'Metang', 'Iron Claw');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('376', '9', 'Metagross', 'Iron Leg');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('377', '9', 'Regirock', 'Rock Peak');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('378', '9', 'Regice', 'Iceberg');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('379', '9', 'Registeel', 'Iron');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('380', '9', 'Latias', 'Eon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('381', '9', 'Latios', 'Eon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('382', '9', 'Kyogre', 'Sea Basin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('383', '9', 'Groudon', 'Continent');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('384', '9', 'Rayquaza', 'Sky High');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('385', '9', 'Jirachi', 'Wish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('386', '9', 'Deoxys', 'DNA');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('387', '9', 'Turtwig', 'Tiny Leaf');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('388', '9', 'Grotle', 'Grove');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('389', '9', 'Torterra', 'Continent');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('390', '9', 'Chimchar', 'Chimp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('391', '9', 'Monferno', 'Playful');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('392', '9', 'Infernape', 'Flame');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('393', '9', 'Piplup', 'Penguin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('394', '9', 'Prinplup', 'Penguin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('395', '9', 'Empoleon', 'Emperor');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('396', '9', 'Starly', 'Starling');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('397', '9', 'Staravia', 'Starling');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('398', '9', 'Staraptor', 'Predator');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('399', '9', 'Bidoof', 'Plump Mouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('400', '9', 'Bibarel', 'Beaver');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('401', '9', 'Kricketot', 'Cricket');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('402', '9', 'Kricketune', 'Cricket');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('403', '9', 'Shinx', 'Flash');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('404', '9', 'Luxio', 'Spark');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('405', '9', 'Luxray', 'Gleam Eyes');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('406', '9', 'Budew', 'Bud');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('407', '9', 'Roserade', 'Bouquet');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('408', '9', 'Cranidos', 'Head Butt');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('409', '9', 'Rampardos', 'Head Butt');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('410', '9', 'Shieldon', 'Shield');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('411', '9', 'Bastiodon', 'Shield');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('412', '9', 'Burmy', 'Bagworm');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('413', '9', 'Wormadam', 'Bagworm');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('414', '9', 'Mothim', 'Moth');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('415', '9', 'Combee', 'Tiny Bee');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('416', '9', 'Vespiquen', 'Beehive');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('417', '9', 'Pachirisu', 'EleSquirrel');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('418', '9', 'Buizel', 'Sea Weasel');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('419', '9', 'Floatzel', 'Sea Weasel');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('420', '9', 'Cherubi', 'Cherry');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('421', '9', 'Cherrim', 'Blossom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('422', '9', 'Shellos', 'Sea Slug');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('423', '9', 'Gastrodon', 'Sea Slug');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('424', '9', 'Ambipom', 'Long Tail');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('425', '9', 'Drifloon', 'Balloon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('426', '9', 'Drifblim', 'Blimp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('427', '9', 'Buneary', 'Rabbit');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('428', '9', 'Lopunny', 'Rabbit');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('429', '9', 'Mismagius', 'Magical');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('430', '9', 'Honchkrow', 'Big Boss');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('431', '9', 'Glameow', 'Catty');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('432', '9', 'Purugly', 'Tiger Cat');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('433', '9', 'Chingling', 'Bell');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('434', '9', 'Stunky', 'Skunk');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('435', '9', 'Skuntank', 'Skunk');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('436', '9', 'Bronzor', 'Bronze');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('437', '9', 'Bronzong', 'Bronze Bell');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('438', '9', 'Bonsly', 'Bonsai');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('439', '9', 'Mime Jr.', 'Mime');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('440', '9', 'Happiny', 'Playhouse');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('441', '9', 'Chatot', 'Music Note');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('442', '9', 'Spiritomb', 'Forbidden');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('443', '9', 'Gible', 'Land Shark');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('444', '9', 'Gabite', 'Cave');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('445', '9', 'Garchomp', 'Mach');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('446', '9', 'Munchlax', 'Big Eater');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('447', '9', 'Riolu', 'Emanation');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('448', '9', 'Lucario', 'Aura');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('449', '9', 'Hippopotas', 'Hippo');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('450', '9', 'Hippowdon', 'Heavyweight');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('451', '9', 'Skorupi', 'Scorpion');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('452', '9', 'Drapion', 'Ogre Scorp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('453', '9', 'Croagunk', 'Toxic Mouth');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('454', '9', 'Toxicroak', 'Toxic Mouth');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('455', '9', 'Carnivine', 'Bug Catcher');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('456', '9', 'Finneon', 'Wing Fish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('457', '9', 'Lumineon', 'Neon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('458', '9', 'Mantyke', 'Kite');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('459', '9', 'Snover', 'Frost Tree');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('460', '9', 'Abomasnow', 'Frost Tree');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('461', '9', 'Weavile', 'Sharp Claw');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('462', '9', 'Magnezone', 'Magnet Area');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('463', '9', 'Lickilicky', 'Licking');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('464', '9', 'Rhyperior', 'Drill');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('465', '9', 'Tangrowth', 'Vine');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('466', '9', 'Electivire', 'Thunderbolt');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('467', '9', 'Magmortar', 'Blast');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('468', '9', 'Togekiss', 'Jubilee');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('469', '9', 'Yanmega', 'Ogre Darner');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('470', '9', 'Leafeon', 'Verdant');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('471', '9', 'Glaceon', 'Fresh Snow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('472', '9', 'Gliscor', 'Fang Scorp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('473', '9', 'Mamoswine', 'Twin Tusk');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('474', '9', 'Porygon-Z', 'Virtual');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('475', '9', 'Gallade', 'Blade');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('476', '9', 'Probopass', 'Compass');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('477', '9', 'Dusknoir', 'Gripper');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('478', '9', 'Froslass', 'Snow Land');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('479', '9', 'Rotom', 'Plasma');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('480', '9', 'Uxie', 'Knowledge');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('481', '9', 'Mesprit', 'Emotion');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('482', '9', 'Azelf', 'Willpower');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('483', '9', 'Dialga', 'Temporal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('484', '9', 'Palkia', 'Spatial');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('485', '9', 'Heatran', 'Lava Dome');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('486', '9', 'Regigigas', 'Colossal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('487', '9', 'Giratina', 'Renegade');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('488', '9', 'Cresselia', 'Lunar');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('489', '9', 'Phione', 'Sea Drifter');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('490', '9', 'Manaphy', 'Seafaring');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('491', '9', 'Darkrai', 'Pitch-Black');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('492', '9', 'Shaymin', 'Gratitude');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('493', '9', 'Arceus', 'Alpha');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('494', '9', 'Victini', 'Victory');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('495', '9', 'Snivy', 'Grass Snake');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('496', '9', 'Servine', 'Grass Snake');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('497', '9', 'Serperior', 'Regal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('498', '9', 'Tepig', 'Fire Pig');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('499', '9', 'Pignite', 'Fire Pig');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('500', '9', 'Emboar', 'Mega Fire Pig');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('501', '9', 'Oshawott', 'Sea Otter');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('502', '9', 'Dewott', 'Discipline');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('503', '9', 'Samurott', 'Formidable');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('504', '9', 'Patrat', 'Scout');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('505', '9', 'Watchog', 'Lookout');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('506', '9', 'Lillipup', 'Puppy');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('507', '9', 'Herdier', 'Loyal Dog');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('508', '9', 'Stoutland', 'Big-Hearted');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('509', '9', 'Purrloin', 'Devious');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('510', '9', 'Liepard', 'Cruel');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('511', '9', 'Pansage', 'Grass Monkey');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('512', '9', 'Simisage', 'Thorn Monkey');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('513', '9', 'Pansear', 'High Temp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('514', '9', 'Simisear', 'Ember');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('515', '9', 'Panpour', 'Spray');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('516', '9', 'Simipour', 'Geyser');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('517', '9', 'Munna', 'Dream Eater');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('518', '9', 'Musharna', 'Drowsing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('519', '9', 'Pidove', 'Tiny Pigeon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('520', '9', 'Tranquill', 'Wild Pigeon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('521', '9', 'Unfezant', 'Proud');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('522', '9', 'Blitzle', 'Electrified');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('523', '9', 'Zebstrika', 'Thunderbolt');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('524', '9', 'Roggenrola', 'Mantle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('525', '9', 'Boldore', 'Ore');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('526', '9', 'Gigalith', 'Compressed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('527', '9', 'Woobat', 'Bat');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('528', '9', 'Swoobat', 'Courting');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('529', '9', 'Drilbur', 'Mole');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('530', '9', 'Excadrill', 'Subterrene');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('531', '9', 'Audino', 'Hearing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('532', '9', 'Timburr', 'Muscular');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('533', '9', 'Gurdurr', 'Muscular');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('534', '9', 'Conkeldurr', 'Muscular');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('535', '9', 'Tympole', 'Tadpole');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('536', '9', 'Palpitoad', 'Vibration');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('537', '9', 'Seismitoad', 'Vibration');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('538', '9', 'Throh', 'Judo');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('539', '9', 'Sawk', 'Karate');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('540', '9', 'Sewaddle', 'Sewing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('541', '9', 'Swadloon', 'Leaf-Wrapped');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('542', '9', 'Leavanny', 'Nurturing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('543', '9', 'Venipede', 'Centipede');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('544', '9', 'Whirlipede', 'Curlipede');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('545', '9', 'Scolipede', 'Megapede');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('546', '9', 'Cottonee', 'Cotton Puff');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('547', '9', 'Whimsicott', 'Windveiled');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('548', '9', 'Petilil', 'Bulb');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('549', '9', 'Lilligant', 'Flowering');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('550', '9', 'Basculin', 'Hostile');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('551', '9', 'Sandile', 'Desert Croc');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('552', '9', 'Krokorok', 'Desert Croc');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('553', '9', 'Krookodile', 'Intimidation');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('554', '9', 'Darumaka', 'Zen Charm');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('555', '9', 'Darmanitan', 'Blazing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('556', '9', 'Maractus', 'Cactus');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('557', '9', 'Dwebble', 'Rock Inn');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('558', '9', 'Crustle', 'Stone Home');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('559', '9', 'Scraggy', 'Shedding');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('560', '9', 'Scrafty', 'Hoodlum');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('561', '9', 'Sigilyph', 'Avianoid');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('562', '9', 'Yamask', 'Spirit');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('563', '9', 'Cofagrigus', 'Coffin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('564', '9', 'Tirtouga', 'Prototurtle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('565', '9', 'Carracosta', 'Prototurtle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('566', '9', 'Archen', 'First Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('567', '9', 'Archeops', 'First Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('568', '9', 'Trubbish', 'Trash Bag');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('569', '9', 'Garbodor', 'Trash Heap');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('570', '9', 'Zorua', 'Tricky Fox');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('571', '9', 'Zoroark', 'Illusion Fox');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('572', '9', 'Minccino', 'Chinchilla');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('573', '9', 'Cinccino', 'Scarf');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('574', '9', 'Gothita', 'Fixation');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('575', '9', 'Gothorita', 'Manipulate');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('576', '9', 'Gothitelle', 'Astral Body');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('577', '9', 'Solosis', 'Cell');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('578', '9', 'Duosion', 'Mitosis');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('579', '9', 'Reuniclus', 'Multiplying');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('580', '9', 'Ducklett', 'Water Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('581', '9', 'Swanna', 'White Bird');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('582', '9', 'Vanillite', 'Fresh Snow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('583', '9', 'Vanillish', 'Icy Snow');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('584', '9', 'Vanilluxe', 'Snowstorm');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('585', '9', 'Deerling', 'Season');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('586', '9', 'Sawsbuck', 'Season');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('587', '9', 'Emolga', 'Sky Squirrel');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('588', '9', 'Karrablast', 'Clamping');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('589', '9', 'Escavalier', 'Cavalry');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('590', '9', 'Foongus', 'Mushroom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('591', '9', 'Amoonguss', 'Mushroom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('592', '9', 'Frillish', 'Floating');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('593', '9', 'Jellicent', 'Floating');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('594', '9', 'Alomomola', 'Caring');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('595', '9', 'Joltik', 'Attaching');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('596', '9', 'Galvantula', 'EleSpider');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('597', '9', 'Ferroseed', 'Thorn Seed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('598', '9', 'Ferrothorn', 'Thorn Pod');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('599', '9', 'Klink', 'Gear');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('600', '9', 'Klang', 'Gear');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('601', '9', 'Klinklang', 'Gear');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('602', '9', 'Tynamo', 'EleFish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('603', '9', 'Eelektrik', 'EleFish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('604', '9', 'Eelektross', 'EleFish');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('605', '9', 'Elgyem', 'Cerebral');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('606', '9', 'Beheeyem', 'Cerebral');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('607', '9', 'Litwick', 'Candle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('608', '9', 'Lampent', 'Lamp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('609', '9', 'Chandelure', 'Luring');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('610', '9', 'Axew', 'Tusk');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('611', '9', 'Fraxure', 'Axe Jaw');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('612', '9', 'Haxorus', 'Axe Jaw');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('613', '9', 'Cubchoo', 'Chill');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('614', '9', 'Beartic', 'Freezing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('615', '9', 'Cryogonal', 'Crystallizing');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('616', '9', 'Shelmet', 'Snail');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('617', '9', 'Accelgor', 'Shell Out');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('618', '9', 'Stunfisk', 'Trap');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('619', '9', 'Mienfoo', 'Martial Arts');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('620', '9', 'Mienshao', 'Martial Arts');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('621', '9', 'Druddigon', 'Cave');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('622', '9', 'Golett', 'Automaton');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('623', '9', 'Golurk', 'Automaton');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('624', '9', 'Pawniard', 'Sharp Blade');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('625', '9', 'Bisharp', 'Sword Blade');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('626', '9', 'Bouffalant', 'Bash Buffalo');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('627', '9', 'Rufflet', 'Eaglet');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('628', '9', 'Braviary', 'Valiant');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('629', '9', 'Vullaby', 'Diapered');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('630', '9', 'Mandibuzz', 'Bone Vulture');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('631', '9', 'Heatmor', 'Anteater');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('632', '9', 'Durant', 'Iron Ant');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('633', '9', 'Deino', 'Irate');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('634', '9', 'Zweilous', 'Hostile');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('635', '9', 'Hydreigon', 'Brutal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('636', '9', 'Larvesta', 'Torch');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('637', '9', 'Volcarona', 'Sun');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('638', '9', 'Cobalion', 'Iron Will');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('639', '9', 'Terrakion', 'Cavern');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('640', '9', 'Virizion', 'Grassland');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('641', '9', 'Tornadus', 'Cyclone');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('642', '9', 'Thundurus', 'Bolt Strike');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('643', '9', 'Reshiram', 'Vast White');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('644', '9', 'Zekrom', 'Deep Black');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('645', '9', 'Landorus', 'Abundance');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('646', '9', 'Kyurem', 'Boundary');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('647', '9', 'Keldeo', 'Colt');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('648', '9', 'Meloetta', 'Melody');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('649', '9', 'Genesect', 'Paleozoic');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('650', '9', 'Chespin', 'Spiny Nut');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('651', '9', 'Quilladin', 'Spiny Armor');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('652', '9', 'Chesnaught', 'Spiny Armor');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('653', '9', 'Fennekin', 'Fox');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('654', '9', 'Braixen', 'Fox');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('655', '9', 'Delphox', 'Fox');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('656', '9', 'Froakie', 'Bubble Frog');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('657', '9', 'Frogadier', 'Bubble Frog');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('658', '9', 'Greninja', 'Ninja');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('659', '9', 'Bunnelby', 'Digging');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('660', '9', 'Diggersby', 'Digging');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('661', '9', 'Fletchling', 'Tiny Robin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('662', '9', 'Fletchinder', 'Ember');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('663', '9', 'Talonflame', 'Scorching');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('664', '9', 'Scatterbug', 'Scatterdust');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('665', '9', 'Spewpa', 'Scatterdust');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('666', '9', 'Vivillon', 'Scale');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('667', '9', 'Litleo', 'Lion Cub');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('668', '9', 'Pyroar', 'Royal');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('669', '9', 'Flabébé', 'Single Bloom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('670', '9', 'Floette', 'Single Bloom');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('671', '9', 'Florges', 'Garden');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('672', '9', 'Skiddo', 'Mount');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('673', '9', 'Gogoat', 'Mount');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('674', '9', 'Pancham', 'Playful');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('675', '9', 'Pangoro', 'Daunting');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('676', '9', 'Furfrou', 'Poodle');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('677', '9', 'Espurr', 'Restraint');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('678', '9', 'Meowstic', 'Constraint');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('679', '9', 'Honedge', 'Sword');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('680', '9', 'Doublade', 'Sword');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('681', '9', 'Aegislash', 'Royal Sword');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('682', '9', 'Spritzee', 'Perfume');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('683', '9', 'Aromatisse', 'Fragrance');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('684', '9', 'Swirlix', 'Cotton Candy');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('685', '9', 'Slurpuff', 'Meringue');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('686', '9', 'Inkay', 'Revolving');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('687', '9', 'Malamar', 'Overturning');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('688', '9', 'Binacle', 'Two-Handed');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('689', '9', 'Barbaracle', 'Collective');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('690', '9', 'Skrelp', 'Mock Kelp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('691', '9', 'Dragalge', 'Mock Kelp');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('692', '9', 'Clauncher', 'Water Gun');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('693', '9', 'Clawitzer', 'Howitzer');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('694', '9', 'Helioptile', 'Generator');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('695', '9', 'Heliolisk', 'Generator');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('696', '9', 'Tyrunt', 'Royal Heir');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('697', '9', 'Tyrantrum', 'Despot');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('698', '9', 'Amaura', 'Tundra');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('699', '9', 'Aurorus', 'Tundra');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('700', '9', 'Sylveon', 'Intertwining');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('701', '9', 'Hawlucha', 'Wrestling');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('702', '9', 'Dedenne', 'Antenna');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('703', '9', 'Carbink', 'Jewel');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('704', '9', 'Goomy', 'Soft Tissue');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('705', '9', 'Sliggoo', 'Soft Tissue');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('706', '9', 'Goodra', 'Dragon');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('707', '9', 'Klefki', 'Key Ring');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('708', '9', 'Phantump', 'Stump');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('709', '9', 'Trevenant', 'Elder Tree');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('710', '9', 'Pumpkaboo', 'Pumpkin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('711', '9', 'Gourgeist', 'Pumpkin');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('712', '9', 'Bergmite', 'Ice Chunk');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('713', '9', 'Avalugg', 'Iceberg');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('714', '9', 'Noibat', 'Sound Wave');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('715', '9', 'Noivern', 'Sound Wave');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('716', '9', 'Xerneas', 'Life');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('717', '9', 'Yveltal', 'Destruction');
insert into pokemon_species_names ("pokemon_species_id", "local_language_id", "name", "genus") values ('718', '9', 'Zygarde', 'Order');
COMMIT;
