BEGIN TRANSACTION;
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('1', 'normal', '1', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('2', 'fighting', '1', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('3', 'flying', '1', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('4', 'poison', '1', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('5', 'ground', '1', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('6', 'rock', '1', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('7', 'bug', '1', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('8', 'ghost', '1', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('9', 'steel', '2', '2');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('10', 'fire', '1', '3');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('11', 'water', '1', '3');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('12', 'grass', '1', '3');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('13', 'electric', '1', '3');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('14', 'psychic', '1', '3');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('15', 'ice', '1', '3');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('16', 'dragon', '1', '3');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('17', 'dark', '2', '3');
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('18', 'fairy', '6', NULL);
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('10001', 'unknown', '2', NULL);
insert into types ("id", "identifier", "generation_id", "damage_class_id") values ('10002', 'shadow', '3', NULL);
COMMIT;
